name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: windows-2016
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docs\windows_setup_script.bat
    - uses: actions/upload-artifact@master
      with:
        name: chocolatey.log
        path: C:\ProgramData\chocolatey\logs\chocolatey.log
