name: Windows Installer Tests

on:
  push:
    paths:
      - .github/workflows/*.yml
      - "**Dockerfile"
      - "**.bat"

jobs:
  test_setup_min:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Test setup script
      run: ./choco_min.bat
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: choco_min.bat.log
        path: C:\ProgramData\chocolatey\logs\chocolatey.log

  test_setup_full:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Test setup script
      run: ./choco_devops.bat
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: choco_devops.bat.log
        path: C:\ProgramData\chocolatey\logs\chocolatey.log

  print_debug_info: 
    runs-on: windows-2019
    steps:
    - name: Print available Windows features
      run: Dism /online /Get-Features
