name: CI tests for dataops-quickstart

on:
  push:
    paths-ignore:
      - docs/**.md
      - "*.md"

jobs:

  test_setup:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Test setup script
      run: docs\windows_setup_script.bat
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: chocolatey.log
        path: C:\ProgramData\chocolatey\logs\chocolatey.log

  # FAILING (timeout error during install):
  test_ssms:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Test SSMS install script
      run: docs\windows_install_ssms.bat
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: chocolatey-ssms.log
        path: C:\ProgramData\chocolatey\logs\chocolatey.log

  test_wsl:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Test WSL install script
      run: docs\windows_install_wsl.bat
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: chocolatey-wsl.log
        path: C:\ProgramData\chocolatey\logs\chocolatey.log

  print_debug_info: 
    runs-on: windows-2019
    steps:
    - name: Print available Windows features
      run: Dism /online /Get-Features
