name: Windows Installer Tests

on:
  push:
    paths:
      - "**.bat"
      - "**onpush.yml"
      - "**Dockerfile"

jobs:

  test_setup:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Test setup script
      run: docs\windows_setup_script.bat
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: chocolatey.log
        path: C:\ProgramData\chocolatey\logs\chocolatey.log

  print_debug_info: 
    runs-on: windows-2019
    steps:
    - name: Print available Windows features
      run: Dism /online /Get-Features

  # test_wsl:
  #   runs-on: windows-2019
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Test WSL install script
  #     run: docker build -f ./.tests/wsl-install-test.Dockerfile .
  #     # run: docs\windows_install_wsl.bat
